// Generated by ToffeeScript 1.6.3-2
var exec, inquirer;

exec = require('child_process').exec;

inquirer = require("inquirer");

module.exports = function(next) {
  var err, gitname, q, response,
    _this = this;
  exec("git config --get --global user.name", function() {
    err = arguments[0], response = arguments[1];
    gitname = null;
    if (!err) {
      gitname = response.replace(/\s+/g, "");
    }
    q = "请输入GitLab用户名";
    if (gitname) {
      q = "" + q + ":[" + gitname + "]";
    }
    return inquirer.prompt([
      {
        name: "username",
        message: q,
        validate: function(username) {
          if (!username || !username.length) {
            if (gitname) {
              return true;
            } else {
              return "请输入GitLab用户名";
            }
          }
          if (username.length < 3) {
            return "用户名长度不小于三位";
          }
          return true;
        }
      }
    ], function(answers) {
      if (!answers.username && gitname) {
        answers.username = gitname;
      }
      mfe.user_conf.reload();
      mfe.user_conf.json.username = answers.username;
      mfe.user_conf.json.init = true;
      return mfe.user_conf.save();
    });
  });
};
