// Generated by ToffeeScript 1.6.3-2
var CmdBase, events, fs, util,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

fs = require('fs');

util = require('util');

events = require("events");

CmdBase = (function(_super) {
  __extends(CmdBase, _super);

  function CmdBase(name, cmd, next) {
    this.name = name;
    this.cmd = cmd;
    this.next = next;
    this.user_conf = mfe.user_conf;
    this.user = this.user_conf.json;
    this.deployDir = "" + mfe.path.work_dir + "/deploy";
  }

  return CmdBase;

})(events.EventEmitter);

module.exports = {};

module.exports.CmdBase = CmdBase;
