// Generated by ToffeeScript 1.6.3-4
(function() {
  var ModuleDeploy, ModulePrepareDirectory, assert, fs, request, util, utils, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ModulePrepareDirectory = require('./ModulePrepareDirectory').ModulePrepareDirectory;

  util = require('util');

  assert = require('assert-plus');

  fs = require('fs');

  request = require('request');

  utils = require('../utils');

  ModuleDeploy = (function(_super) {
    __extends(ModuleDeploy, _super);

    function ModuleDeploy() {
      _ref = ModuleDeploy.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ModuleDeploy.prototype.templatesServerConfig_ = function(cb) {
      var body, channelId, deployContent, deployFilename, error, response, uname, work_dir,
        _this = this;
      if (!this.cmd.deploy) {
        this.cmd.deploy = "templates_server";
        if (this.cmd.optimize && this.cmd.optimize.indexOf("D" !== -1)) {
          this.cmd.optimize = "D" + this.cmd.optimize;
        } else {
          this.cmd.optimize = "D";
        }
        work_dir = mfe.path.work_dir;
        uname = mfe.user_conf.json.username;
        channelId = this.cmd.channel === true ? uname : "" + uname + "_" + this.cmd.channel;
        deployContent = "{\n    \"domain\": \"http://sts0.mofang.com\",\n    \"receiver_statics\": \"http://qiniu\",\n    \"output_statics\": \"qiniu\",\n    \"receiver_templates\": \"http://templates.mofang.com/receiver.php\",\n    \"output_templates\": \"channel/" + channelId + "\",\n    \"name\": \"templates_server\"\n}";
        deployFilename = "" + work_dir + "/deploy/" + uname + "/templates_server.json";
        fs.writeFileSync(deployFilename, deployContent);
        if (this.cmd.channel) {
          console.log("\n正在使用模板服务器，通道:【" + channelId + "】\n");
        }
        if (!this.cmd.cleanup) {
          cb();
          return true;
        }
        request("http://templates.mofang.com/api/clean_channel.php?channel=" + channelId, function() {
          error = arguments[0], response = arguments[1], body = arguments[2];
          if (error) {
            console.log("cleanup error:" + error);
            process.exit();
          }
          if (response.statusCode !== 200) {
            console.log("templates server response code:" + response.statusCode);
            process.exit();
          }
          if (body !== "0") {
            console.log("remove folder error,response code:" + body);
            process.exit();
          }
          if (body === "0") {
            console.log("清空通道" + channelId + "部署完成.");
            return cb();
          } else {
            console.log("moduleDeploy.js:unknown error.");
            return process.exit();
          }
        });
      } else {
        return cb();
      }
    };

    ModuleDeploy.prototype.prepareComplete = function(cb) {
      var answer, body, channelId, cmd, cmds, content, err, error, filename, main_cmd, moduleName, out, response, uname,
        _this = this;
      assert.func(cb);
      if (!this.cmd.deploy) {
        return cb("部署标识未指定 -d <name>");
      }
      if (this.cmd.online && this.cmd["package"]) {
        return this.next("不能同事使用--online 和--package参数");
      }
      if (this.cmd.online || this.cmd["package"]) {
        if (!this.cmd.channel) {
          return this.next("请填写要部署到的通道编号:例如12");
        }
      }
      if (this.cmd.online) {
        utils.ask_if_v(("直接上线:将要通过模板服务器将模块【" + this.module + "】及相关资源直接到线上,请确认操作").green, function() {
          err = arguments[0], answer = arguments[1];
          _$$_2();
        });
      } else if (this.cmd["package"]) {
        utils.ask_if_v(("与代码同步上线:将打包模块【" + this.module + "】及相关资源到线上,并生成模板部署id,请确认操作").yellow, function() {
          err = arguments[0], answer = arguments[1];
          _$$_2();
        });
      } else if (this.cmd.deploy === "templates_server") {
        utils.ask_if_v(("将要以上线标准部署模块【" + this.module + "】到模板服务器,以便通过模板服务器预览线上效果,请确认操作").blue, function() {
          err = arguments[0], answer = arguments[1];
          _$$_2();
        });
      } else {
        utils.ask_if_v(("警告:将要以【" + this.cmd.deploy + "】规则,部署模块【" + this.module + "】及相关资源到线上,模块和部署标识是否正确").red, function() {
          err = arguments[0], answer = arguments[1];
          _$$_2();
        });
      }
      function _$$_2() {
        var _i, _len, _ref1;
        if (!answer) {
          return _this.next("模块【" + _this.module + "】的部署操作取消");
        }
        cmds = [];
        _ref1 = mfe.defaultModules;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          moduleName = _ref1[_i];
          if (_this.module !== moduleName && moduleName !== "mfe") {
            cmd = "mfe release -r " + moduleName;
            if (_this.cmd.deploy) {
              cmd += " -d " + _this.cmd.deploy + "_statics," + _this.cmd.deploy + "_templates";
            }
            if (_this.cmd.optimize) {
              cmd += " -" + _this.cmd.optimize;
              cmd += " --verbose";
            }
            cmd += " -moDup";
            cmds.push(cmd);
          }
        }
        main_cmd = "mfe release -r " + _this.module;
        if (_this.cmd.deploy) {
          main_cmd += " -d " + _this.cmd.deploy + "_statics," + _this.cmd.deploy + "_templates";
        }
        if (_this.cmd.optimize) {
          main_cmd += " -" + _this.cmd.optimize;
          main_cmd += " --verbose";
        }
        main_cmd += " -moDup";
        cmds.push(main_cmd);
        content = "" + (cmds.join("\n"));
        filename = "" + mfe.path.work_dir + "/release.sh";
        fs.writeFileSync(filename, content);
        fs.chmodSync(filename, "777");
        utils.work_dir_shell2(cmds, function() {
          err = arguments[0], out = arguments[1];
          fs.writeFileSync('v.log', out);
          if (_this.cmd["package"]) {
            uname = mfe.user_conf.json.username;
            channelId = _this.cmd.channel === true ? uname : "" + uname + "_" + _this.cmd.channel;
            request("http://templates.mofang.com/api/package_pre_release.php?channel=" + channelId, function() {
              error = arguments[0], response = arguments[1], body = arguments[2];
              if (error) {
                console.log("package templates error: " + error);
                process.exit();
              }
              if (response.statusCode !== 200) {
                console.log("package templates response code: " + response.statusCode);
                process.exit();
              }
              response = JSON.parse(body);
              if (response.code) {
                if (response.error) {
                  console.log("package templates error: " + response.error);
                }
              } else {
                console.log("package templates error: unknown");
                process.exit();
                console.log("\n模板ID: " + response.data + "\n");
                fs.writeFileSync('template_id.txt', "" + response.data + "\n");
              }
              _$$_1();
            });
          } else {
            _$$_1();
          }
          function _$$_1() {
            if (_this.cmd.online) {
              uname = mfe.user_conf.json.username;
              channelId = _this.cmd.channel === true ? uname : "" + uname + "_" + _this.cmd.channel;
              request("http://templates.mofang.com/api/package_release.php?channel=" + channelId, function() {
                error = arguments[0], response = arguments[1], body = arguments[2];
                if (error) {
                  console.log("release package error: " + error);
                  process.exit();
                }
                if (response.statusCode !== 200) {
                  console.log("release package error: " + response.statusCode);
                  process.exit();
                }
                response = JSON.parse(body);
                if (response.code) {
                  if (response.error) {
                    console.log("release package error: " + response.error);
                  }
                } else {
                  console.log("release package error: unknown");
                  process.exit();
                }
                console.log("\n模板版本: " + response.data + "\n");
                fs.writeFileSync('templates_version.txt', "" + response.data + "\n");
                _$$_0();
              });
            } else {
              _$$_0();
            }
            function _$$_0() {
              return cb(null);
            };
          };
        });
      };
    };

    return ModuleDeploy;

  })(ModulePrepareDirectory);

  module.exports = {};

  module.exports.ModuleDeploy = ModuleDeploy;

}).call(this);
