// Generated by ToffeeScript 1.6.3-1
var GitManager, ModuleList, NameModuleBase, assert, async, gitManager, ok, utils,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

NameModuleBase = require('./ModuleBase').NameModuleBase;

GitManager = require('../GitManager');

gitManager = new GitManager();

ok = require('okay');

assert = require('assert-plus');

async = require('async');

utils = require('../utils');

ModuleList = (function(_super) {
  __extends(ModuleList, _super);

  function ModuleList(module, cmd, next) {
    ModuleList.__super__.constructor.call(this, module, cmd, next);
  }

  ModuleList.prototype.onDirExists_ = function() {
    var _this = this;
    return gitManager.getModuleNames(function(err, names) {
      console.log(names.join(" , "));
      return _this.next;
    });
  };

  return ModuleList;

})(NameModuleBase);

module.exports = {};

module.exports.ModuleList = ModuleList;
