// Generated by ToffeeScript 1.6.3-1
var CmdBase, Project, util,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

util = require('util');

CmdBase = require('./CmdBase').CmdBase;

Project = (function(_super) {
  __extends(Project, _super);

  function Project(name, cmd, next) {
    Project.__super__.constructor.call(this, name, cmd, next);
    console.log("Project.js not implement");
  }

  return Project;

})(CmdBase);

module.exports.Project = Project;
