// Generated by ToffeeScript 1.6.3-2
var CmdBase, Upgrade, exec, util,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

exec = require('child_process').exec;

util = require('util');

CmdBase = require('./CmdBase').CmdBase;

Upgrade = (function(_super) {
  __extends(Upgrade, _super);

  function Upgrade(name, cmd, next) {
    var child, cmd_upgrade;
    Upgrade.__super__.constructor.call(this, name, cmd, next);
    cmd_upgrade = "cd " + mfe.path.cli + " npm unlink . && git fetch --all  && git reset --hard origin/master && npm link .";
    child = exec(cmd_upgrade, function(err, stdout, stderr) {
      var packageInfo, version;
      if (err) {
        return next("git更新仓库失败.");
      } else {
        packageInfo = require("" + mfe.path.cli + "/package.json");
        version = packageInfo.version;
        return next(null, version);
      }
    });
  }

  return Upgrade;

})(CmdBase);

module.exports = {};

module.exports.Upgrade = Upgrade;
